/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './agents/index.html',
    './ai-token/index.html',
    './hardware/index.html',
    './agent-detail/index.html',
    './order/index.html',
    './about/index.html',
    './src/**/*.{js,html}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim': '#b3c5ff',
        'surface-tint': '#0054d7',
        'on-tertiary-fixed': '#00201c',
        'on-tertiary-container': '#f3fffb',
        'secondary-container': '#38a6fd',
        'on-primary-fixed': '#001849',
        'on-error': '#ffffff',
        'inverse-surface': '#2d3133',
        'surface-variant': '#e0e3e6',
        'on-primary': '#ffffff',
        primary: '#0052d1',
        'surface-bright': '#f7f9fc',
        'on-tertiary-fixed-variant': '#005048',
        'on-error-container': '#93000a',
        'secondary-fixed': '#d0e4ff',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        'inverse-on-surface': '#eff1f4',
        'primary-container': '#1769ff',
        'inverse-primary': '#b3c5ff',
        'on-secondary-fixed-variant': '#004a79',
        'on-primary-fixed-variant': '#003fa5',
        'surface-container-lowest': '#ffffff',
        background: '#f7f9fc',
        'on-surface-variant': '#424655',
        'outline-variant': '#c2c6d8',
        'surface-dim': '#d8dadd',
        'secondary-fixed-dim': '#9acbff',
        surface: '#f7f9fc',
        'tertiary-container': '#008377',
        'primary-fixed': '#dbe1ff',
        'on-primary-container': '#fefbff',
        'surface-container-high': '#e6e8eb',
        tertiary: '#00685e',
        'tertiary-fixed': '#5cfae7',
        'error-container': '#ffdad6',
        'surface-container-low': '#f2f4f7',
        error: '#ba1a1a',
        'on-background': '#191c1e',
        'tertiary-fixed-dim': '#33ddcb',
        secondary: '#00629f',
        'on-surface': '#191c1e',
        'surface-container': '#eceef1',
        'on-secondary-fixed': '#001d34',
        'surface-container-highest': '#e0e3e6',
        outline: '#737687',
        'on-secondary-container': '#003a60',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        unit: '8px',
        'max-width': '1440px',
        'margin-desktop': '64px',
        gutter: '24px',
      },
      fontFamily: {
        'headline-md': ['Geist', 'PingFang SC', 'Microsoft YaHei', 'sans-serif'],
        'body-md': ['Inter', 'PingFang SC', 'Microsoft YaHei', 'sans-serif'],
        'hero-md': ['Geist', 'PingFang SC', 'Microsoft YaHei', 'sans-serif'],
        'hero-mobile': ['Geist', 'PingFang SC', 'Microsoft YaHei', 'sans-serif'],
        'headline-lg': ['Geist', 'PingFang SC', 'Microsoft YaHei', 'sans-serif'],
        'body-lg': ['Inter', 'PingFang SC', 'Microsoft YaHei', 'sans-serif'],
        'hero-lg': ['Geist', 'PingFang SC', 'Microsoft YaHei', 'sans-serif'],
        'label-sm': ['Geist', 'PingFang SC', 'Microsoft YaHei', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'hero-md': ['56px', { lineHeight: '1.2', letterSpacing: '-0.015em', fontWeight: '700' }],
        'hero-mobile': ['40px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'hero-lg': ['72px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      maxWidth: {
        'max-width': '1440px',
      },
    },
  },
  plugins: [],
}
